### ISSUE TITLE
P3P All Lods Failed Validation, cannot write P3D with 0 Lods[Bug] 

### ISSUE THREAD

**Issue by Crash357** [MrClock8163/Arma3ObjectBuilder#60]
### Add-on version

Release

### Description

Blender 3.6,4.0,4.1 i can not export my models in P3D alway error Validation failed . 
[kitchen_3.zip](https://github.com/MrClock8163/Arma3ObjectBuilder/files/15453881/kitchen_3.zip)

### Steps to reproduce

Load the file into blender and try export as P3D

### Stack trace

```shell
bpy.ops.object.join()
bpy.context.space_data.context = 'DATA'
bpy.context.object.a3ob_properties_object.is_a3_lod = True
bpy.ops.object.transform_apply()
P3D - All LODs failed validation, cannot write P3D with 0 LODs (check the system console)
bpy.ops.a3ob.export_p3d(filepath="P:\\pry-Dayz-Modding\\Archipack\\bungalow_Proxy_TEST.p3d")
bpy.ops.object.transform_apply()
P3D - All LODs failed validation, cannot write P3D with 0 LODs (check the system console)
bpy.ops.a3ob.export_p3d(filepath="P:\\pry-Dayz-Modding\\Archipack\\bungalow_Proxy_TEST.p3d")
```

### Contact details

heinz.schnicke@gmail.com

**Comment by MrClock8163** [comment]
@Crash357 
I looked at the file you attached, and I have to say, this is not an issue with the plugin.
If you run the validation on the model manually, you'll see it fails because it has n-gons:

![kép](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/48679831/dc03793a-5257-4798-9919-dcc544af7ecc)

The P3D file format does not support faces with more than 4 vertices. You'll have to resolve this issue before exporting it to P3D.

![kép](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/48679831/8dec3799-2cbf-4a94-ac4f-971b644e2722)

**Comment by MrClock8163** [comment]
You'll have to fix the topology, so that it only contains triangles and quads. The lazy solution would be to apply a triangulation modifier, but I **highly** suggest you research the topic further on forums and tutorials, as you obviously lack basic knowledge required here.

**Comment by Crash357** [comment]
Thx .

Am Mo., 3. Juni 2024 um 16:57 Uhr schrieb MrClock ***@***.***
