### ISSUE TITLE
[Bug]  Problem interacting with objects

### ISSUE THREAD

**Issue by DerKamade** [MrClock8163/Arma3ObjectBuilder#64]
### Blender version

4.1.1

### Add-on version

Release

### Description

Hello, I've encountered a problem where after loading an add-on, I can no longer interact with objects anywhere. Clicking in the viewport and the outliner doesn't allow me to select objects. In edit mode, all faces are selected and I can't separately select what I need. Disabling the add-on makes everything work again.
Additionally, I am unable to rotate, resize, or move objects.

![image](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/93059327/28b2e4ee-1ba9-44a2-ad39-36bfe7830e66)
![image](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/93059327/2b23f7b3-28e4-4546-828c-65eabf98a894)

### Steps to reproduce

Load the addon and try to interact with objects

**Comment by MrClock8163** [comment]
@DerKamade 
I cannot reproduce your issue on 4.1.1 with v2.3.3 of the addon.
I'd like to ask some additional information:
- linux or windows
- addon version
- other addons you have loaded

**Comment by MrClock8163** [comment]
Looking at what you sent, I'm pretty sure your installation is messed up one way or another.
A couple of notes:
- ArmaToolbox and Arma 3 Object Builder (my addon) are mutually exclusive. You either use one or the other. Having both installed is just asking for trouble.
- `blender-p3d-import-export-master` is not for Arma 3 P3D files. Just want to note this in case you missed it.
- `rtm_import` only works with the ArmaToolbox not Arma 3 Object Builder. It also might not be compatible with Blender 4.1.1. It was originally developed for Blender 2.80, and hasn't been updated since.
- Judging from the 4 warnings in the System Console, something is broken with your installation of the ArmaToolbox addon. Some of its files seem to be in the addon root directory, instead of the ArmaToolbox folder.

**Comment by DerKamade** [comment]
> Глядя на то, что вы отправили, я почти уверен, что ваша установка так или иначе испорчена. Пара замечаний:
> 
> * ArmaToolbox и Arma 3 Object Builder (мой аддон) являются взаимоисключающими. Вы либо используете одно, либо другое. Установка обоих просто напрашивается на неприятности.
> * `blender-p3d-import-export-master`не предназначен для файлов Arma 3 P3D. Просто хочу отметить это, если вы пропустили это.
> * `rtm_import`работает только с ArmaToolbox, а не с Arma 3 Object Builder. Он также может быть несовместим с Blender 4.1.1. Первоначально он был разработан для Blender 2.80 и с тех пор не обновлялся.
> * Судя по 4 предупреждениям в системной консоли, что-то не так с установкой дополнения ArmaToolbox. Некоторые из его файлов находятся в корневом каталоге аддона, а не в папке ArmaToolbox.

Thank you for your help. I cleared the cache from the %appdata% folder and the configs and add-ons. Of course, all settings reverted to default, but everything works now. Thanks! You have great mods for Arma, and I was very happy to talk with you.
